### ISSUE TITLE
Will the site ever work again?

### ISSUE THREAD

**Issue by CostaCiruela** [jiornojiovanni/creamapidb#24]
As the title says, I want to know if it is possible to get the site working again. I know it's a short time to ask, but I don't have any information about it and I don't know how to get it either. I used to use this site a lot, it was much easier than using the original program.

**Comment by jiornojiovanni** [comment]
Sorry, the domain expired 🥲

You can use this link that points directly to the heroku instance https://creamapidb.herokuapp.com/

I should probably update the readme.
