### ISSUE TITLE
the site is down

### ISSUE THREAD

**Issue by rasbayri** [jiornojiovanni/creamapidb#25]

**Comment by jiornojiovanni** [comment]
I set up another server, everything should work now. This is the new link https://creamapidb.publicvm.com/

**Comment by rasbayri** [comment]
Uh... the another problem is, whatever game I pick, all it do is says "Game could not be stuffed", could you please fix that?

**Comment by jiornojiovanni** [comment]
Works for me tho.. Can you give me a list of the games that don't work so I can try them?

**Comment by rasbayri** [comment]
- Strange telephone
- Gurobu
- Monster Prom
and etc. there are too many of them! And I really love your tool....

> Works for me tho.. Can you give me a list of the games that don't work so I can try them?

**Comment by jiornojiovanni** [comment]
Fixed. Try it and let me know :)

**Comment by rasbayri** [comment]
It's working!
